### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by Nasdrovia69** [Kangie/sddm-sugar-candy#5]
after installing boot screen i can't log in "login failed" i managed to reboot and i changed the screen to the original one and i managed to reboot and log in

**Comment by Dregen-Yor** [comment]
I have the same problem too.

**Comment by Nasdrovia69** [comment]
For me it is solved but I do not know any more how that happened I believe that I uninstalled and reinstalled but I am not any more on that it goes back.
I'm running fedora Kde 39

**Comment by Dregen-Yor** [comment]
I just found a way to solve this problem.
vim /usr/share/sddm/themes/sugar-candy/theme.conf
And then change the AllowBadUsernames into "true".
Then the problem fixed

**Comment by Nasdrovia69** [comment]
Thank you for this solution, in case the problem recurs.   ;-)
