### ISSUE TITLE
qtgraphicaleffects is not installed

### ISSUE THREAD

**Issue by ishyy1** [Kangie/sddm-sugar-candy#8]
Hi, When I boot my pc up the sddm theme switches to the default one and I get an error that says something along the lines of "qtgraphicaleffects is not installed" even tho i have qt5-qtgraphicaleffects installed

**Comment by Nocturnussx** [comment]
same here using fedora and  qt5-qtgraphicaleffects is installed on my system

**Comment by nevermore23274** [comment]
I believe I'm having the same issue as the two above. The exact error reads:
```
The current theme cannot be loaded due to the errors below, please select another theme.

file:///usr/share/sddm/themes/simple-sddm/Main.qml:28:1:module "QtGraphicalEffects" is not installed
```
I'm on Fedora 40 and using Hyprland (specifically https://github.com/JaKooLit/Fedora-Hyprland )

Though perhaps to give a bit more information than "doesn't work, help" I ran `cat /usr/share/sddm/themes/simple-sddm/metadata.desktop` which yielded:
```sh
[SddmGreeterTheme]
Name=Tokyo Night SDDM
Description=A Tokyo Night Theme for SDDM
Author=rototrash
License=GPL-3.0-or-later
Type=sddm-theme
Version=1.0
Website=https://github.com/tokyo-night-sddm/
Screenshot=preview.png
MainScript=Main.qml
ConfigFile=theme.conf
Theme-Id=tokyo-night-sddm
```

First thing noted was the Main.qml as the main script, and opening that up with `nano /usr/share/sddm/themes/simple-sddm/Main.qml` the first thing I see is`This file is part of SDDM Sugar Candy.`

**Comment by Nasdrovia69** [comment]
> I believe I'm having the same issue as the two above. The exact error reads:
> 
> ```
> The current theme cannot be loaded due to the errors below, please select another theme.
> 
> file:///usr/share/sddm/themes/simple-sddm/Main.qml:28:1:module "QtGraphicalEffects" is not installed
> ```
> 
> I'm on Fedora 40 and using Hyprland (specifically https://github.com/JaKooLit/Fedora-Hyprland )
> 
> Though perhaps to give a bit more information than "doesn't work, help" I ran `cat /usr/share/sddm/themes/simple-sddm/metadata.desktop` which yielded:
> 
> ```shell
> [SddmGreeterTheme]
> Name=Tokyo Night SDDM
> Description=A Tokyo Night Theme for SDDM
> Author=rototrash
> License=GPL-3.0-or-later
> Type=sddm-theme
> Version=1.0
> Website=https://github.com/tokyo-night-sddm/
> Screenshot=preview.png
> MainScript=Main.qml
> ConfigFile=theme.conf
> Theme-Id=tokyo-night-sddm
> ```
> 
> First thing noted was the Main.qml as the main script, and opening that up with `nano /usr/share/sddm/themes/simple-sddm/Main.qml` the first thing I see is`This file is part of SDDM Sugar Candy.`

Same for me and qt5-qtgraphicaleffects is installed, who provide Qtgraphicaleffects component
version 5.15.13
maybe I do mistake

**Comment by nickholden-ui** [comment]
Here is a fix

Replace QtGraphicalEffects with  Qt5Compat.GraphicalEffects in all the qml files that ref it

You can run this 

cd /usr/share/sddm/themes/sddm-sugar-candy

sudo find . -type f -name "*.qml" -exec sed -i 's/import QtGraphicalEffects 1.0/import Qt5Compat.GraphicalEffects/g' {} +

Then test with 
sddm-greeter --test-mode --theme /usr/share/sddm/themes/sddm-sugar-candy/

**Comment by Carlisle96** [comment]
After fixing the issue, unfortunately, I get this strange emtpy profile picture ( I don't want any picture at all ), which breaks the aesthetic of the theme: 
![image](https://github.com/Kangie/sddm-sugar-candy/assets/33028362/95596481-f5b1-4973-a5bb-1b014b5cfdec)

Any Ideas ?

**Comment by tukykarmakar** [comment]
I think that's an icon that's not resolving properly, but I don't know for sure. I tried changing the path to the .svgz file inside the .qml file, but it's not changing to the image that I'm setting. The file is at `/usr/share/sddm/themes/sugar-candy/Components/UserList.qml` and the section of the code for that button is below--
```
indicator: Button {
                id: usernameIcon
                width: selectUser.height * 0.8
                height: parent.height
                anchors.left: parent.left
                anchors.verticalCenter: parent.verticalCenter
                anchors.leftMargin: selectUser.height * 0.125
                icon.height: parent.height * 0.25
                icon.width: parent.height * 0.25
                enabled: false
                icon.color: root.palette.text
                icon.source: Qt.resolvedUrl("../Assets/User.svgz")
        }
```

**Comment by Durlyn** [comment]
ListItem.qml has nothing to do with it.
This button is described in Input.qml

            indicator: Button {
                    id: usernameIcon
                    width: selectUser.height * 0.8
                    height: parent.height
                    anchors.left: parent.left
                    anchors.verticalCenter: parent.verticalCenter
                    anchors.leftMargin: selectUser.height * 0.125
                    icon.height: parent.height * 0.25
                    icon.width: parent.height * 0.25
                    enabled: false
                    icon.color: root.palette.text
                    icon.source: Qt.resolvedUrl("../Assets/User.svgz")
                   background: Rectangle {
                        color: "transparent"
                    }
            }

I added a background area with the color transparent

**Comment by Carlisle96** [comment]
> I added a background area with the color transparent

It fixed it for me:
![image](https://github.com/Kangie/sddm-sugar-candy/assets/33028362/6fa5e455-38ba-48a7-bb79-015ce3672934)

Do you know why there is a small "t" showing on the left ?

**Comment by Durlyn** [comment]
I don't know how to properly solve this problem.
I walked around it this way.
added font size to ComboBox area

        ComboBox {

            id: selectUser

            width: parent.height
            height: parent.height
            anchors.left: parent.left
            font.pointSize: 1      // <- this code

**Comment by Carlisle96** [comment]
Thanks !

**Comment by tukykarmakar** [comment]
Only adding the rectangle with transparent background was enough. However, the icon is not centred on horizontal axis. I don't mind, but just letting people know.
![image](https://github.com/Kangie/sddm-sugar-candy/assets/42614682/cc86e797-a09f-4d29-8b17-f33ae1d289a2)

> Do you know why there is a small "t" showing on the left ?

That's the first letter of your username @Carlisle96. It shows the first letter of my username too (which is not 't').

**Comment by Kangie** [comment]
This is not my code, I just uploaded it (unchanged) because I needed to add some tags for packaging.

> That's the first letter of your username @Carlisle96. It shows the first letter of my username too (which is not 't').

I maintain a fork [sddm-eucalyptus-drop](https://gitlab.com/Matt.Jolly/sddm-eucalyptus-drop) which should fix at least this issue.

**Comment by Kangie** [comment]
https://gitlab.com/Matt.Jolly/sddm-eucalyptus-drop/-/commit/c29d518ee5098cc05458b80ccf5a83c2a9822d57 includes the required fixes.

**Comment by Kangie** [comment]
> After fixing the issue, unfortunately, I get this strange emtpy profile picture ( I don't want any picture at all ), which breaks the aesthetic of the theme: ![image](https://private-user-images.githubusercontent.com/33028362/335853061-95596481-f5b1-4973-a5bb-1b014b5cfdec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMzUwODEsIm5iZiI6MTcyMDMzNDc4MSwicGF0aCI6Ii8zMzAyODM2Mi8zMzU4NTMwNjEtOTU1OTY0ODEtZjViMS00OTczLWE1YmItMWIwMTRiNWNmZGVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDA2NDYyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNDg3NjBlMWE1MjQwOTg5NGMyYWY1YTJiMGU2YWQ1MzA2YWYzNGM5NzdlZGZjNDliYTY1ODk4MjNiZTZhOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HRgXsS2O_x1E3Wca0e8BY954ltMezDDJjvB7nrZfTNM)
> 
> Any Ideas ?

You need to add the 'flat' property to each of the buttons, or just use the updated fork :)
